file = open("administrador.py", "r")
print(file.read(10))
print("##############")
print(file.readline())
print(file.readline())
print("##############")
print(file.read())
print("##############")
file = open("administrador.py", "r")
print(file.readlines())